config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users

  resources :products do
    resources :comments
  end

  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

  post 'payments/create'

  root 'static_pages#index'

  mount ActionCable.server => '/cable'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xavier Bike Shop</title>
     <%= csrf_meta_tags %>

	  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

  </head>

  <body>

     <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="nav-container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Bike Shop Berlin', static_pages_index_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li id="nav-link"><%= link_to 'Home', static_pages_index_path %></li>
            <li id="nav-link"><%= link_to 'Bikes', products_path %></li>
            <li id="nav-link"><%= link_to 'About', static_pages_about_path %></li>
            <li id="nav-link"><%= link_to 'Contact', static_pages_contact_path %></li>
            <li id="nav-link"><a href="https://xavierblog.herokuapp.com/">Blog</a></li>
          </ul>
          <ul class="nav navbar-nav navlogin">
            <li>
            <% if user_signed_in? %>
              <%= link_to('Logout: '+@current_user_email, destroy_user_session_path, :method => :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path) %>
            <% end %>
            </li>
          </ul>
          <%= form_tag("/products", class: "navbar-form navbar-right", role: "search", method: "get") do %>
            <div class="form-group">
             <%= label_tag(:q, "", class: "search-bar-label") %>
              <%= text_field_tag(:q, nil, class: "form-control", placeholder: "Search for...") %>
            </div>
            <%= submit_tag("Search", class: "btn btn-default btn-search") %>
          <% end %>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <p id="cable-notice" style="display:none" class="alert alert-info"></p>

    <% if notice %>
    <p id="notice" class="alert alert-info"><%= notice %></p>
    <% end %>

    <% if alert %>
    <p id="alert" class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

    <footer class="site-footer">
    	<div id="copyright">
  		&copy; 2016 Bike Shop Berlin
  		</div>
		</footer>

  </body>
</html>